### ISSUE TITLE
Tests For This Lab Need To Be Re-examined

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-3-ruby-oo-self-cash-register-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/5286/assignments/172711?module_item_id=376669

### Concern

This lab's 'test' suite spazzes out only within two initialized instance variables in:

After only doing the following, it spazzes out with a non-correct error:
```
class CashRegister
  attr_accessor :total, :discount

  def initialize(discount)
    @total = 0
    @discount = discount
  end

end
```

Related test output that is incorrect:
```
samuelbanya@Samuels-MBP ~/hub/Development/code/phase-3/phase-3-ruby-oo-self-cash-register-lab $ learn test --f-f

CashRegister
  .new
    sets an instance variable @total on initialization to zero (FAILED - 1)

Failures:

  1) CashRegister .new sets an instance variable @total on initialization to zero
     Failure/Error:
       def initialize(discount)
         @total = 0
         @discount = discount
       end
     
     ArgumentError:
       wrong number of arguments (given 0, expected 1)
     # ./lib/cash_register.rb:4:in `initialize'
     # ./spec/cash_register_spec.rb:2:in `new'
     # ./spec/cash_register_spec.rb:2:in `block (2 levels) in <top (required)>'
     # ./spec/cash_register_spec.rb:7:in `block (3 levels) in <top (required)>'

Finished in 0.00179 seconds (files took 0.1044 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/cash_register_spec.rb:6 # CashRegister .new sets an instance variable @total on initialization to zero
```

**Comment by lizbur10** [comment]
Hi @SamuelBanya! The error is due to the fact that the `discount` parameter needs to be optional. I have reordered the test to make that clearer.

Thanks as always for contributing to the Flatiron School curriculum 💙
